models = [
    """
    CREATE TABLE FDOC (
        DNUM INT PRIMARY KEY,
        DCANT VARCHAR(100),
        DFECHA VARCHAR(100),
        DVENCE VARCHAR(100),
        DIVA VARCHAR(100),
        DDESC VARCHAR(100),
        DBRUTO VARCHAR(100),
        DCANTF VARCHAR(100),
        DREFER VARCHAR(100),
        DREFERELLOS VARCHAR(100),
        DESCXC VARCHAR(100),
        DESINV VARCHAR(100),
        DESFACT VARCHAR(100),
        DPAR1 VARCHAR(100),
        DPAR3 VARCHAR(100),
        CLICOD VARCHAR(100)

    );
    """,
    """
    CREATE TABLE FAXINV(
        ICOD VARCHAR(100),
        FMOV VARCHAR(100),
        AITIPMV VARCHAR(100),
        AIPRECIO VARCHAR(100),
        AICOSTO VARCHAR(100),
        AIPREBR VARCHAR(100),
        AIPZAS VARCHAR(100),
        AIDESCTO VARCHAR(100),
        AICANTF VARCHAR(100),
        AIMES VARCHAR(100),
        AIALMACEN VARCHAR(100),
        AIPED VARCHAR(100),
        AIUSEQ VARCHAR(100)
    );
    """,

    """
    CREATE TABLE FINV(
        ICOD VARCHAR(100),
        IDESCR VARCHAR(100),
        ITIPO VARCHAR(100),
        ILISTA3 VARCHAR(100),
        IFAM1 VARCHAR(100),
        IFAM2 VARCHAR(100),
        IFAM3 VARCHAR(100),
        IFAM4 VARCHAR(100),
        IFAM5 VARCHAR(100),
        IFAM6 VARCHAR(100),
        IMINIMO VARCHAR(100),
        IMAXIMO VARCHAR(100),
        ITIEMPO VARCHAR(100)
    );
    """,
    """
    CREATE TABLE FCLI(
        CLICOD VARCHAR(100),
        CLINOM VARCHAR(100),
        CLIDIR VARCHAR(100),
        CLICD VARCHAR(100),
        CLIEDO VARCHAR(100),
        CLISTA VARCHAR(100),
        CLICREDIT VARCHAR(100),
        CLIPLAZO0 VARCHAR(100),
        CLIDIREV VARCHAR(100),
        CLISACT VARCHAR(100),
        CLIRFC VARCHAR(100),
        CLIALTA VARCHAR(100),
        CLIOBS VARCHAR(100),
        CLICTA VARCHAR(100)
    );
    """

]